# -*- coding: utf-8 -*-
"""Lab1_official.R

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zH6FjmN0EItfm0zVm1oyv6Cwxuk0E-Jt

<!-- # ---
# title: "Do Democrats or Republicand Experience More Difficulty Voting?"
# subtitle: "Datasci 203 Lab 1"
# author: "Indri Adisoemarta, Ishani P. Cheshire, Nadaa Moharram"
# output:
#   bookdown::pdf_document2:
#     toc: true
#     number_sections: true
# --- -->

# Lab 1

## Introduction

The right to vote is a cornerstone of American democracy—yet, in recent years, many have questioned whether this right is truly being protected by our current policies. From attempts to purge voter rolls (Cole, 2024), to laws in Georgia criminalizing the handing out of food and water to voters waiting in line (ACLU, 2021), high-profile cases of voter suppression have rocketed the topic to the forefront of our national debate. Partisan groups often claim that voter suppression tactics are politically motivated, and affect one party more than the other. Given the extreme closeness of US national elections—some estimates put the number of swing state votes truly deciding US presidential elections as low as 150,000 (Hernandez, 2024)—even small differences in voter suppression across party lines could have far-reaching consequences for our elections. To begin to address this issue, of interest to politicians and voting rights groups alike,
we ask the following question:

*Do Democratic voters or Republican voters experience more difficulty voting?*

The answer to this question will have material significance to voter's rights activists and other groups seeking to protect the people's right to vote, as well as political campaigns which have a vested interest in maintaining fair and free elections.
"""

library(tidyverse)
library(dplyr)

# read in data
anes_2022_data <- read.csv("anes_pilot_2022_csv_20221214.csv")

anes_2022_data_initial_subset <- select(anes_2022_data, reg, regdiff, caseid, votehard, house22p, senate22p, gov22p, vote20, vote24dt, pid1d, pid1r, pidlean, vharder_1, vharder_4, vharder_5)

df_coded <- anes_2022_data_initial_subset

# create function that codes for D=democrat or R=republican based on house/senate/gov voting history
recode_party_vote_hist <- function(x) {
  x <- ifelse(x == 1, "D", x)
  x <- ifelse(x == 2, "R", x)
  return(x)
}

# create function that codes for D=democrat or R=republican based on presidential election choice and leaning
recode_party_vote_pres <- function(x) {
  x <- ifelse(x == 1, "R", x)
  x <- ifelse(x == 2, "D", x)
  return(x)
}

# identify Democrats and Republican options based on voting history
df_coded[, c("house22p", "senate22p", "gov22p", "pid1d", "pid1r")] <- lapply(df_coded[, c("house22p", "senate22p", "gov22p", "pid1d", "pid1r")], recode_party_vote_hist)

# identify Democrats and Republicans based on pres election and leaning
df_coded[, c("vote20", "vote24dt", "pidlean")] <- lapply(df_coded[, c("vote20", "vote24dt", "pidlean")], recode_party_vote_pres)

# function to calculate D and R scores
count_values <- function(row, values_to_count) {
 sum(row %in% values_to_count)
}

df_coded$D_count <- apply(df_coded, 1, count_values, "D")

df_coded$R_count <- apply(df_coded, 1, count_values, "R")

# if D_count > R_count = Democrat, if D_count < R_count = Republican, else = other
df_coded <- df_coded %>%
  mutate(party = case_when(
    D_count > R_count ~ "Democrat",
    D_count < R_count ~ "Republican",
    D_count == R_count ~ "Other"
  ))

table(df_coded$party)
table(df_coded$reg)

head(df_coded)

"""## Data

Our data is from the American National Election Studies (ANES) 2022 Pilot Study, which aimed to gauge voting patterns and public opinion following the 2022 midterm elections. The survey was conducted online via YouGov, a platform where users sign up to fill out surveys for pay. Due to being an online platform whose user base is self-selecting, the YouGov user base are not entirely representative of the US population—however, the data may still hold important insights, and will be a valuable case study to motivate later, more representative studies. We will draw from the 1,585 respondents who finished the survey in its entirety when conducting our analysis.

In order to determine respondents' difficulty to vote, we will be primarily using the responses to the survey question, "How difficult was it for you to vote?" which yields a Likert variable (1-5) ranging from "Not difficult at all" to "Extremely difficult." One issue with the responses to this question is that the ANES survey did not show this question to respondents who reported that they did not vote. Therefore, these responses are missing a potentially significant demographic—people who might have attempted to vote, but found it so difficult that they were unable to. Also missing are people who could not register to vote due to difficulty, who were filtered out at an even earlier stage. We could attempt some sort of synthesis of earlier questions, assuming the highest values of difficulty for people who reported either not voting or not registering to vote. However, this method is flawed, as we cannot know the true reason why an individual did not vote. For this reason, we must neglect the 417 respondents who did not answer the difficulty question—leaving us with 1168 remaining respondents. Due to this limitation on the available data for difficulty to vote, we are forced to define a 'voter' as someone who has voted, rather than someone who had the potential to vote (all citizens over 18).
<!-- fill in: put this below the part where we calculate these values so I can code in the counts rather than having to hard-code it -->

In order to determine which respondents fall into the category of Democratic voters vs. Republican voters, we  turn to established methods of determining voter affiliation. Petrocik (2009) examined the tendency of many American voters to identify as independent, while having a clearly partisan voting history. For this reason, we take into account not just the respondent's self-identification but their reported previous voting history. To determine a respondent's true party leaning, we first count how many times a respondent voted for a Democratic candidate, tallying up their Democrat 'points.' Finally, we add an additional point if the individual's self-identified as such, creating the Democratic point total. We then do the same for their Republican 'points.' We then compare the two point totals, and classify the respondent into a party depending on the higher total. An individual with equal points will be labeled an independent, and not used in our analysis. Of our respondents, 32 were classified as independent using this method, leaving a final 1136 respondents who lean either Democrat or Republican and responded to the survey's difficulty question.

<!-- (put plot below?) -->
"""

# drop rows with votehard -1
df_coded_votehard_filt <- df_coded[df_coded$votehard != "-1", ]

"""## Methods

We will refer to the difficulty of voting experienced by Democrats as the random variable $X$, while the difficulty of voting experienced by Republicans is described by a random variable $Y$. The Wilcoxon Rank Sum Test Hypothesis of Comparisons is the most appropriate test for our data set. First, the test is intended for unpaired data, like ours. Second, the test can be used for non-parametric data, meaning it makes no assumptions about the shape of the underlying distribution of data—which is good, as we don't have enough information to assume normality across our Likert scale. Furthermore, the Hypothesis of Comparisons version allows for ordinal variables, meaning our Likert scale data can be used.

To use the Wilcoxon Rank Sum Test Hypothesis of Comparisons, we must make two assumptions. First, that our data is ordinal, which as a Likert variable, it is. Second, that our data is IID. While YouGov's respondents are not strictly independent, as users can recommend the site to other users, YouGov's user base is in the millions and surveys are often sent out randomly to users who meet certain given criteria (e.g. being a US citizen.) Therefore, a lack of independence is unlikely. Regarding whether our data is identically distributed, when we look at the histogram below of difficulty values separated by party, we see that lower indications of difficulty tend to be higher, and vica versa. We notice no distinct substructure. Given our large sample size of 1,136, one would expect that is there was any distinct clusterings of subgroups with differing underlying distributions, they would be clear in this plot. Therefore, we have no evidence suggesting that our data is not identically distributed—for our X and Y random variables separately. Therefore, we will assume IID.
<!-- fill in: code in values -->

<!-- fill in: insert plot below -->


"""

ggplot(df_coded_votehard_filt, aes(x = votehard, fill = party)) +
  geom_bar(position = "dodge") +  # Creates separate bars for each party
  scale_fill_manual(values = c("Democrat" = "blue", "Republican" = "red", "Other" = "grey")) +  # Custom party colors
  labs(title = "Difficulty by Party",
       x = "Difficulty Level",
       y = "Count") +
  theme_minimal() +
  theme(legend.title = element_blank())  # Removes legend title

"""We start with a null hypothesis that Democrats and Republicans experience similar levels of difficulty voting, or, more explicitly, that the probability that a draw from $X$ ranks higher than a draw from $Y$ is the same as the probability that a draw from $X$ ranks higher than a draw from $Y$ ($P(X>Y) = P(Y>X)$). For this we will pursue a two-sided test. We decide on a threshold p-value of $0.05$, as is industry standard, below which we will reject our $H_0$ in favor of our alternate hypothesis, that Democrats and Republicans experience different levels of difficulty voting $P(X>Y) \neq P(Y>X)$."""

head(df_coded)

democrats <- filter(df_coded_votehard_filt, party=="Democrat")
republicans <- filter(df_coded_votehard_filt, party=="Republican")

"""## Results"""

result = wilcox.test(democrats$votehard, republicans$votehard, paired = FALSE)
print(result)

"""We find that the two-sided Wilcoxon Rank Sum Test supports rejecting our null hypothesis (p = `r result$p.value` < 0.05) in favor of our alternative hypothesis that $P(X>Y) \neq P(Y>X)$. This value is definitely statistically significant, as it is multiple orders of magnitude below our threshold value of $0.05$.

<!-- fill in: code in values -->
"""

# more parameters two-sided test
result = wilcox.test(democrats$votehard, republicans$votehard, mu=0, alt="two.sided", conf.int = T, paired = FALSE)
print(result)

# try a one-sided test to see what the difference is
# alternative hypothesis is that democrats have greater difficulty
one_sided_result_1 = wilcox.test(democrats$votehard, republicans$votehard, alt="greater", conf.int = T, paired = FALSE)
print(one_sided_result_1)

# alternative hypothesis is that democats have less difficulty
one_sided_result_2 = wilcox.test(democrats$votehard, republicans$votehard, alt="less", conf.int = T, paired = FALSE)
print(one_sided_result_2)

D_hard <- sum(democrats$votehard >= 3)
R_hard <- sum(republicans$votehard >= 3)

percen_D_hard <- round(100*D_hard/nrow(df_coded_votehard_filt), 2)
percen_R_hard <- round(100*R_hard/nrow(df_coded_votehard_filt), 2)
diff_percen_hard <- percen_D_hard - percen_R_hard
scale_US = round(345997551*diff_percen_hard/100)

"""In order to investigate which group experiences more difficulty voting, we conduct two one-sided Wilcoxon Rank Sum Tests in order to see which alternative hypothesis, $P(X>Y) > P(Y>X)$ or $P(X>Y) < P(Y>X)$, is more likely given our data. We find $P(X>Y) < P(Y>X)$ to be more likely (`r one_sided_result_2$p.value` > `r one_sided_result_1$p.value`).

<!-- fill in: code in values -->

Some may argue that the practical significance of this effect will depend on how much the expectation values of the two groups truly differ—that a very small difference in means is unlikely to have practical significance. We can assess the practical significance of this effect by estimating the amount of Democrats that experience significant difficulty voting in comparison to the amount of Republicans. We define significant difficulty voting as a Likert value of >3. The number of Democrats with a difficulty rating >3 is `r D_hard`, or `r percen_D_hard`% of our total sample. The number of Republicans with a difficulty rating >3 is `r R_hard`, or `r percen_R_hard`% of our total sample. The discrepancy between these two percentages is `r diff_percen_hard`%, which could represent `r scale_US` voters if we scale to the US population.

As previously discussed, even 150,000 swing state voters can alter the results of the US national elections. Therefore, our results are definitely practically significant. There remain some limitations to our result—for instance, this survey was not collected on a representative sample, making our conclusions not actually generalizable to the national population. However, these results are still a good initial step in this analysis, and will provide insight to inform the design of more representative studies in the future.

## Conclusion
This study found evidence not only that Democrats and Republicans experience unequal levels of difficulty voting, but that Democrats tend to experience more difficulty. This result is both statistically and practically significant—making it of interest to voting rights activists and lawmakers alike. Still, there are  limitations on our work—the YouGov dataset is not fully representative of the US population, and the survey's structure excludes some of the most suppressed voters from our sample, such as those who did not manage to actually vote. This analysis is only the first step in this investigation—in the future, we hope to incorporate demographic weights into our analysis to make our sample more representative, as well as finding ways to estimate the lower and upper bounds on those groups whose views were not captured by the ANES survey.
"""

# replace those that did not vote with the hardest difficulty
df_recode_didnotvote <- df_coded

df_recode_didnotvote$votehard <- ifelse(df_recode_didnotvote$votehard == -1, 5, df_recode_didnotvote$votehard)

table(df_recode_didnotvote$votehard)

democrats_w_nonvoters <- filter(df_recode_didnotvote, party=="Democrat")
republicans_w_nonvoters <- filter(df_recode_didnotvote, party=="Republican")

result_nonvoters_hardest = wilcox.test(democrats_w_nonvoters$votehard, republicans_w_nonvoters$votehard, mu=0, alt="two.sided", paired = FALSE)
print(result_nonvoters_hardest)

# replace those that did not vote with medium difficulty
df_recode_didnotvote_med <- df_coded

df_recode_didnotvote_med$votehard <- ifelse(df_recode_didnotvote_med$votehard == -1, 3, df_recode_didnotvote_med$votehard)

table(df_recode_didnotvote_med$votehard)

democrats_w_nonvoters_med <- filter(df_recode_didnotvote_med, party=="Democrat")
republicans_w_nonvoters_med <- filter(df_recode_didnotvote_med, party=="Republican")

result_nonvoters_med = wilcox.test(democrats_w_nonvoters_med$votehard, republicans_w_nonvoters_med$votehard, mu=0, alt="two.sided", paired = FALSE)
print(result_nonvoters_med)

"""## Future Work

We mentioned early on in our data section that the difficulty survey question was not shown to people who did not vote. This is a potentially significant demographics because these people might have attempted to vote, but found it so difficult that they were actually unable to. However, as we cannot know the true reason why any of these people did not vote, we chose to exclude them from our analysis. In this way, our sample is potentially missing data on the groups who may have found the voting process the most difficult.

We attempted to rectify this oversight by estimating the most extreme case in either direction for this population of respondents. First, we considered the case where all non-voters had the most difficult time voting, assigning them the highest value of the Likert scale possible. Then, we considered the case where all non-voters had a neither particularly difficult nor particularly easy time voting, assigning them the middle of the Likert scale. (We did not choose the lowest Likert value here due to our presumption that non-voters are not likely to find voting especially easy and convenient.)

We then replicated the same Wilcoxon Signed Rank Sum test that we conducted above, but on these two new samples. Our goal was to use these two most extreme cases to establish an upper and lower boundary on our previous p-value, and to see if this uncaptured population had the potential to shift our analysis to the point of no longer being able to reject our null hypothesis. We were surprised to find that both of our extremity calculations yielded p-values high enough ($p_{\text{hardest\_difficulty}}$ = `r result_nonvoters_hardest$p.value`, $p_{\text{medium\_difficulty}}$ = `r result_nonvoters_med$p.value`) to fail to nullify our null hypothesis of equality between the groups.

Both extreme cases failing is somewhat unexpected, as one would think that the extreme case in one direction would shift the p-value higher, while the extreme case in the other direction would shift the p-value lower. One explanation for this could be that, in the process of this calculation, we overly contaminated our real sample by assigning identical data to the Democrats and Republicans, artificially shifting their Likert distributions closer together. Regardless, this finding makes clear the fact that for any future studies on voting difficulty, the subset of non-voters must be considered and surveyed—as their presence is quite substantial and has the potential to significantly alter our results.

## References
ACLU. 2021, ACLU. https://www.aclu.org/news/civil-liberties/block-the-vote-voter-suppression-in-2020

Cole, D. 2024, CNN. https://www.cnn.com/2024/09/20/politics/attempts-to-purge-voter-rolls-increase-as-election-nears/index.html

Hernandez, J. 2024, NPR. https://www.npr.org/2024/08/29/nx-s1-4936052/swing-states-presidential-elections

Petrocik, J. 2009, Electoral Studies, 28, 562, doi: 10.1016/j.electstud.2009.05.022
"""

